### ISSUE TITLE
Problems installing Req on fly.io

### ISSUE THREAD

**Issue by Calamari** [wojtekmach/req#169]
Hiho. Thanks for this nice library. It really is neat and I like how it simplifies things.

But, I somehow don't get it to work on my fly.io hosted Phoenix app, and am a bit fuzzy what I am missing.

If I deploy the app it fails deploying with those lines:

```
 2023-02-25T09:33:37.701 app[5f5ab2c4] fra [info] Preparing to run: `/app/entry eval MyApp.Release.migrate` as nobody
2023-02-25T09:33:37.722 app[5f5ab2c4] fra [info] 2023/02/25 09:33:37 listening on [fdaa:0:3afd:a7b:67:5f5a:b2c4:2]:22 (DNS: [fdaa::3]:53)
2023-02-25T09:33:40.770 app[5f5ab2c4] fra [info] 09:33:40.766 [info] Migrations already up
2023-02-25T09:33:40.822 app[5f5ab2c4] fra [info] ** (ArgumentError) unknown registry: Req.Finch
2023-02-25T09:33:40.822 app[5f5ab2c4] fra [info] (elixir 1.13.0) lib/registry.ex:1343: Registry.key_info!/1
2023-02-25T09:33:40.822 app[5f5ab2c4] fra [info] (elixir 1.13.0) lib/registry.ex:576: Registry.lookup/2
2023-02-25T09:33:40.822 app[5f5ab2c4] fra [info] lib/finch/pool_manager.ex:44: Finch.PoolManager.lookup_pool/2
2023-02-25T09:33:40.822 app[5f5ab2c4] fra [info] lib/finch/pool_manager.ex:34: Finch.PoolManager.get_pool/2
2023-02-25T09:33:40.822 app[5f5ab2c4] fra [info] lib/finch.ex:284: Finch.__stream__/5
2023-02-25T09:33:40.822 app[5f5ab2c4] fra [info] lib/finch.ex:324: anonymous fn/4 in Finch.request/3
2023-02-25T09:33:40.822 app[5f5ab2c4] fra [info] (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
2023-02-25T09:33:40.822 app[5f5ab2c4] fra [info] lib/req/steps.ex:579: Req.Steps.run_finch/1
2023-02-25T09:33:41.716 app[5f5ab2c4] fra [info] Starting clean up.
```

So I somehow tried to put  `{Finch, name: Req.Finch}` into my `application.ex` file which did not change anything and I also tried to put `extra_applications: [:req]` into my mix.exs file, since I saw that there is a `Req.Application` that does that. But nothing changed. 

It works superbly if I start the app locally. I am probably missing something obvious but I don't see it. Any idea?

**Comment by wojtekmach** [comment]
:extra_applications is for apps that are not dependencies, i.e. Elixir or OTP apps, so changing that wouldn't have an effect. I can see you're using Elixir releases so try staring the release locally and see if you can reproduce? In general this error would occur when Req application isn't started. For example, if you do:

```bash
bin/myapp eval 'Req.get!("https://elixir-lang.org")'
```

this would crash with this error because `bin/myapp eval` does NOT start your application and none of the deps are started either.

Hope this helps!

**Comment by Calamari** [comment]
Yes, it did point me to the right problem/solution.

Only to disover that I have another problem with IPv6s and immediate closing connections. But after investigating quite a bit, I am still a bit clueless where the problem is (If here, or Finch or Mint, or even an infrastructure problem)? So I didn't write another Issue. But this one is closed. Thanks.
