### ISSUE TITLE
0.4.0 breaks `Inspect` protocol when `req` is a nested dependency

### ISSUE THREAD

**Issue by cschmatzler** [wojtekmach/req#238]
The introduction of the `Req.MixProject.legacy_headers_as_lists?/0` check breaks inspecting anything `Req`-related when `req` is the dependency of a dependency.

## Steps to reproduce

1. Create an empty library called `foo`.
2. Add `req` 0.4.0 as a dependency to `foo`.
3. Create another project `bar` and add `foo` as a dependency.
4. Inside `bar`, run `Req.new([]) |> IO.inspect()`

## Expected behavior

The `Inspect` protocol works and we can look into `Req.Request` and `Req.Response`.

## Actual behavior

```elixir
iex(1)> Req.new([]) |> IO.inspect()
#Inspect.Error<
  got UndefinedFunctionError with message:

      """
      function Req.MixProject.legacy_headers_as_lists?/0 is undefined (module Req.MixProject is not available)
      """

  while inspecting:

      %{
        async: nil,
        private: %{},
        options: %{},
        __struct__: Req.Request,
        into: nil,
        body: nil,
        halted: false,
        url: %URI{
          scheme: nil,
          userinfo: nil,
          host: nil,
          port: nil,
          path: nil,
          query: nil,
          fragment: nil
        },
        adapter: &Req.Steps.run_finch/1,
        headers: %{},
        method: :get,
        current_request_steps: [:put_user_agent, :compressed, :encode_body,
         :put_base_url, :auth, :put_params, :put_path_params, :put_range, :cache,
         :put_plug, :compress_body],
        error_steps: [retry: &Req.Steps.retry/1],
        registered_options: MapSet.new([:form, :location_trusted, :receive_timeout,
         :pool_timeout, :compressed, :decode_body, :redirect_log_level,
         :retry_log_level, :connect_options, :retry_delay, :max_retries,
         :follow_redirects, :redirect_trusted, :plug, :finch, :path_params, :base_url,
         :finch_request, :cache, :json, :user_agent, :unix_socket, :decode_json,
         :params, :auth, :max_redirects, :inet6, :cache_dir, :output, :raw,
         :compress_body, :range, :http_errors, :retry, :redirect]),
        request_steps: [
          put_user_agent: &Req.Steps.put_user_agent/1,
          compressed: &Req.Steps.compressed/1,
          encode_body: &Req.Steps.encode_body/1,
          put_base_url: &Req.Steps.put_base_url/1,
          auth: &Req.Steps.auth/1,
          put_params: &Req.Steps.put_params/1,
          put_path_params: &Req.Steps.put_path_params/1,
          put_range: &Req.Steps.put_range/1,
          cache: &Req.Steps.cache/1,
          put_plug: &Req.Steps.put_plug/1,
          compress_body: &Req.Steps.compress_body/1
        ],
        response_steps: [
          retry: &Req.Steps.retry/1,
          redirect: &Req.Steps.redirect/1,
          decompress_body: &Req.Steps.decompress_body/1,
          decode_body: &Req.Steps.decode_body/1,
          handle_http_errors: &Req.Steps.handle_http_errors/1,
          output: &Req.Steps.output/1
        ]
      }

  Stacktrace:

    Req.MixProject.legacy_headers_as_lists?()
    (req 0.4.0) lib/req/request.ex:1027: Inspect.Req.Request.inspect/2
    (elixir 1.15.4) lib/inspect/algebra.ex:348: Inspect.Algebra.to_doc/2
    (elixir 1.15.4) lib/io.ex:458: IO.inspect/3
    (stdlib 5.0.2) erl_eval.erl:746: :erl_eval.do_apply/7
    (elixir 1.15.4) src/elixir.erl:361: :elixir.eval_forms/4
    (elixir 1.15.4) lib/module/parallel_checker.ex:112: Module.ParallelChecker.verify/1
    (iex 1.15.4) lib/iex/evaluator.ex:331: IEx.Evaluator.eval_and_inspect/3
    (iex 1.15.4) lib/iex/evaluator.ex:305: IEx.Evaluator.eval_and_inspect_parsed/3
    (iex 1.15.4) lib/iex/evaluator.ex:294: IEx.Evaluator.parse_eval_inspect/4
    (iex 1.15.4) lib/iex/evaluator.ex:187: IEx.Evaluator.loop/1
    (iex 1.15.4) lib/iex/evaluator.ex:32: IEx.Evaluator.init/5
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3

>
```

**Comment by wojtekmach** [comment]
Thank you for the report, 0.4.1 is out with the fix.
