### ISSUE TITLE
Mint.TransportError - socket closed

### ISSUE THREAD

**Issue by sergiotapia** [wojtekmach/req#312]
`(Mint.TransportError) socket closed\\n    (req 0.4.8) lib/req.ex:1029: Req.request!/`

It's quite hard to find a repro for this bug it's frequent enough that it shows up regularly on my Oban jobs and even when running code in `iex -S mix phx.server`. To fix I just need to re-run it, or let the Oban job retry.

![image](https://github.com/wojtekmach/req/assets/686715/e7fdfe96-0c24-44ad-b9e3-c226b6cca341)

Any ideas why this would happen so frequently? Again, I appreciate it's hard to debug without more repro steps but happy to figure out how to find that repro case!

Urls where this happens:

OpenAI's API, HowLongtoBeat's API, Target's RedSky API.

**Comment by jozuas** [comment]
I can quite easily replicate this issue. Just reload the module that makes a `Req` request in an iex session. For me, after the code reload, I get `socket closed`.

**Comment by wojtekmach** [comment]
For anyone running into this issue, please see https://github.com/sneako/finch/pull/273#issuecomment-2144879631, you can test it by setting Finch dependency to:

```elixir
{:finch, github: "keathley/finch", branch: "handle-idle-connections", override: true}
```

**Comment by sergiotapia** [comment]
This is still happening very frequently. I'm calling Req.post from Oban jobs and it happens quite a lot. 

```
Req.post(@base_url,
  headers: headers,
  json: body
)

"** (Req.TransportError) socket closed
    (req 0.5.6) lib/req.ex:1092: Req.request!/2
```

**Comment by mrkaspa** [comment]
I have the same issue, I have a lot of logs with this error message:

```
** (Mint.TransportError) socket closed

Req.retry/3: Got exception. Will retry in 0ms, 1 attempt left
```

does that mean that the request failed and it is going to retry it? or that it failed completely?

**Comment by wojtekmach** [comment]
It means the the request will be retried.

**Comment by wojtekmach** [comment]
Hey Amadeus, long time no see! Nothing comes to mind however if you are able to consistently reproduce this issue it’d be really appreciated if you could debug this by removing layers, if you can’t reproduce reproduce the same error using Finch directly then that’s a sign the problem is not in Req. And then if you can reproduce the problem with using Mint directly, maybe it’s a matter of socket configuration. Worth using different http clients and seeing if you can reproduce this.

One Oban specific piece of advice, Req does retries by default for GET requests, Oban jobs tend to do retries too so you might be retrying more than expected.

**Comment by badosu** [comment]
> Hey Amadeus, long time no see!

Glad to see you too! I was wondering if you'd remember, I'm very happy to see you so active in this community I've joined a couple years ago, keep it up!

> One Oban specific piece of advice, Req does retries by default for GET requests, Oban jobs tend to do retries too so you might be retrying more than expected.

Yes, we're aware. Our critical non-idempotent jobs are not allowed to be retried unless carefully inspected to be safe to do so, what exacerbates this issue for us, since we have to track every instance of this error occurring or to allow retries for this case.

For non critical jobs (still not idempotent, we don't allow retries) we're considering introduce this option (keep get and head as they are, allow retry on any `:econnrefused | :closed`) to test out if the issue is mitigated:

```elixir
retry: fn
  _request, %Req.TransportError{reason: reason}
  when reason in [:closed, :econnrefused] ->
    true

  %Req.Request{method: method}, error
  when not is_struct(error, Req.Response) and method in [:get, :head] ->
    true

  _request, _response_or_error ->
    false
end
```

**Comment by kzemek** [comment]
This is anecdata, but this was a big issue for us, and it seemed to happen only for connections to particular upstream servers (most notably Anthropic API). We couldn't find a root cause in reasonable time, so we switched to HTTPoison for these problematic connections.

**Comment by badosu** [comment]
> We couldn't find a root cause in reasonable time, so we switched to HTTPoison for these problematic connections.

Would you mind sharing whether switching to httpoison decreased the perceived (or hard data if you got) amount of timeouts?
