### ISSUE TITLE
get request fails for jpeg image when using with IO.stream()

### ISSUE THREAD

**Issue by sezaru** [wojtekmach/req#348]
If I try to download the following image using a normal get request, it works fine:

```elixir
Req.get!("https://s3.amazonaws.com/core-marketplace-appointment-prod/uploads/af34444b-8599-4f58-b306-d75dc7b17250/images/af34444b-8599-4f58-b306-d75dc7b17250_20240507165221504430.jpg")
#Req.Response<
  status: 200,
  headers: %{
    "accept-ranges" => ["bytes"],
    "content-type" => ["image/jpg"],
    "date" => ["Fri, 10 May 2024 15:49:02 GMT"],
    "etag" => ["\"6892a2057a722bda0ac88af805af9fb9\""],
    "last-modified" => ["Tue, 07 May 2024 16:52:22 GMT"],
    "server" => ["AmazonS3"],
    "x-amz-id-2" => ["zaHxiP4aAhMN+dRM5Er2f+Hv7l7wpD7UvjXTee5PBspRw4I1sqPJLTZd8lEvk70ZrJ3hCX3ggQw="],
    "x-amz-request-id" => ["3PHKJVHS8J0316HC"],
    "x-amz-server-side-encryption" => ["AES256"]
  },
  body: <<255, 216, 255, 224, 0, 16, 74, 70, 73, 70, 0, 1, 1, 0, 0, 72, 0, 72,
    0, 0, 255, 225, 0, 140, 69, 120, 105, 102, 0, 0, 77, 77, 0, 42, 0, 0, 0, 8,
    0, 5, 1, 18, 0, 3, 0, 0, 0, ...>>,
  trailers: %{},
  private: %{},
  ...
>
```

Now, if I try the same request, but I want to get a stream from it, I will get the following error:

```elixir
iex(7)> Req.get!("https://s3.amazonaws.com/core-marketplace-appointment-prod/uploads/af34444b-8599-4f58-b306-d75dc7b17250/images/af34444b-8599-4f58-b306-d75dc7b17250_20240507165221504430.jpg", into: IO.stream())
** (ArgumentError) argument error
    (stdlib 5.2) io.erl:103: :io.put_chars(:standard_io, <<255, 216, 255, 224, 0, 16, 74, 70, 73, 70, 0, 1, 1, 0, 0, 72, 0, 72, 0, 0, 255, 225, 0, 140, 69, 120, 105, 102, 0, 0, 77, 77, 0, 42, 0, 0, 0, 8, 0, 5, 1, 18, 0, 3, 0, 0, 0, 1, 0, 1, ...>>)
    (req 0.4.14) lib/req/steps.ex:898: anonymous fn/3 in Req.Steps.finch_stream_into_collectable/5
    (finch 0.18.0) lib/finch.ex:364: anonymous fn/3 in Finch.stream/5
    (finch 0.18.0) lib/finch/http1/conn.ex:346: Finch.HTTP1.Conn.receive_response/8
    (finch 0.18.0) lib/finch/http1/conn.ex:131: Finch.HTTP1.Conn.request/8
    (finch 0.18.0) lib/finch/http1/pool.ex:60: anonymous fn/10 in Finch.HTTP1.Pool.request/6
    (nimble_pool 1.0.0) lib/nimble_pool.ex:349: NimblePool.checkout!/4
    (finch 0.18.0) lib/finch/http1/pool.ex:52: Finch.HTTP1.Pool.request/6
    (finch 0.18.0) lib/finch.ex:423: anonymous fn/6 in Finch.stream_while/5
    (telemetry 1.2.1) /var/home/sezdocs/projects/rebuilt/platform/core/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (req 0.4.14) lib/req/steps.ex:907: Req.Steps.finch_stream_into_collectable/5
    (req 0.4.14) lib/req/request.ex:993: Req.Request.run_request/1
    (req 0.4.14) lib/req/request.ex:938: Req.Request.run/1
    (req 0.4.14) lib/req.ex:994: Req.request!/2
```

**Comment by wojtekmach** [comment]
We can’t write non printable characters to stdout, this is the same outcome if you tried doing something like

    File.read!("1.jpg") |> IO.write()

FWIW with Req can stream _to_ file:

    into: File.stream!("out.jpg")
