### ISSUE TITLE
Allow to set the body in `merge_options`?

### ISSUE THREAD

**Issue by binajmen** [wojtekmach/req#382]
I'm wrapping an API and want to create a convenient client. To achieve this, I'm trying to incrementally build a request that can handle all the requests I'll need to perform.

However, I haven't found a way to set the body as form-encoded or JSON (depending on the API's design/needs).

Here are my attempts at setting a form-encoded body:

```elixir
defmodule Client do
  @rpc_endpoint "..."

  def new_request(method, path) do
    Req.Request.new(method: method, url: @rpc_endpoint <> path)
  end

  def set_bearer(request, token) do
    Req.Request.merge_options(request, auth: {:bearer, token})
  end

  def set_form(request, payload) do
    # First try

    Req.Request.merge_options(request, form: payload)
    # ** (ArgumentError) unknown option :form
    #     (req 0.3.12) lib/req/request.ex:803: Req.Request.validate_options/2
    #     (req 0.3.12) lib/req/request.ex:566: Req.Request.merge_options/2

    # Second try

    Req.Request.merge_options(request, body: {:form, payload})
    # warning: Passing :body is deprecated, use Req.update/2 instead.
    #   (req 0.3.12) lib/req/request.ex:557: Req.Request.merge_options/2
    #
    # ** (KeyError) key :body not found in: {%Req.Request{
    #    method: :post,
    #    url: URI.parse("https://api.dropboxapi.com/2/oauth2/token"),
    #    headers: [],
    #    body: nil,

    # Third try

    Req.update(request, body: {:form, payload})
    # ** (ArgumentError) errors were found at the given arguments:

    #   * 1st argument: not an iodata term

    #     :erlang.iolist_size({:form, %{...}})
    #     (mint 1.6.2) lib/mint/http1.ex:1039: anonymous fn/1 in Mint.HTTP1.add_content_length_or_transfer_encoding/2
  end

  def set_json(request, payload) do
    Req.Request.merge_options(request, json: payload)
  end

  def run_request(request) do
    Req.Request.run_request(request)
  end
end
```

The end goal is to be able to build the request like so:
```elixir
new_request(:post, "/some/path")
|> set_bearer(...)
|> set_form(%{...})
|> run_request()
```

**Comment by binajmen** [comment]
I can do this instead:
```elixir
  def set_form(request, payload) do
    Req.update(request, body: URI.encode_query(payload))
  end

  def set_json(request, payload) do
    Req.update(request, body: Jason.encode_to_iodata!(payload))
  end
``` 
But by doing so I'm bypassing Req and the nice things like automatic response body decoding.

**Comment by binajmen** [comment]
I'm sorry for the noise, it seems updating Req solved my issue 👀
